version: "3.1"

services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        env_file:
            - .env
        networks:
            - app-network
        volumes:
            - app-db-data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - app-network
    app:
        build: .
        env_file:
            - .env
        environment:
            - APP_PORT=6969
            - APP_HOST=0.0.0.0
            - POSTGRES_HOST=db
        ports:
            - 6969:6969
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    app-db-data:
